### ISSUE TITLE
Backup Policy unable to take Sanpshot of Reserved Instances

### ISSUE THREAD

**Issue by mkatkade** [cmachler/aws-lambda-ebs-backups#10]
Hi @cmachler ,

I have created Backup and Retention policy for my EC2 instances.  The policy is executing successfully, however it is unable to find any instance in any regions. I have 80 instances running in "US East (N. Virginia)" regions and all instances are reserved. 
PFA screenshot for reference and kindly suggest 
<img width="1421" alt="ebs-backup-1" src="https://user-images.githubusercontent.com/27006492/27782747-645b92f0-5ff1-11e7-8af3-cc91b247a706.png">
<img width="1009" alt="ebs-backup-2" src="https://user-images.githubusercontent.com/27006492/27782746-645b6a6e-5ff1-11e7-90ed-59c3a4227b5e.png">
<img width="1101" alt="ebs-backup-3" src="https://user-images.githubusercontent.com/27006492/27782748-645d393e-5ff1-11e7-8b6d-8b5d0a294fea.png">

if any changes are required for reserved instances.

**Comment by cmachler** [comment]
You may want to check you have correct role assigned in the function. For troubleshooting you may want to create a test script to just print out the instances, and start troubleshooting. From what info you have provided I would have to guess its permissions related. I am closing the issue since I believe its permissions issue on your side, and you will need to troubleshoot that.

![screenshot from 2017-07-12 06-00-14](https://user-images.githubusercontent.com/15955897/28116735-b51dcdb6-66c7-11e7-8b9d-2e9df4ab2ac1.png)
